// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	. "github.com/cyril-jump/gofermart/internal/dto"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/user/balance)
	GetUserBalance(ctx echo.Context) error

	// (POST /api/user/balance/withdraw)
	PostUserBalanceWithdraw(ctx echo.Context) error

	// (POST /api/user/login)
	PostUserLogin(ctx echo.Context) error

	// (GET /api/user/orders)
	GetUserOrders(ctx echo.Context) error

	// (POST /api/user/orders)
	PostUserOrders(ctx echo.Context) error
	// User registration
	// (POST /api/user/register)
	PostUserRegister(ctx echo.Context) error

	// (GET /api/user/withdrawals)
	GetUserBalanceWithdrawals(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetUserBalance converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserBalance(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserBalance(ctx)
	return err
}

// PostUserBalanceWithdraw converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserBalanceWithdraw(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserBalanceWithdraw(ctx)
	return err
}

// PostUserLogin converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserLogin(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserLogin(ctx)
	return err
}

// GetUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserOrders(ctx)
	return err
}

// PostUserOrders converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserOrders(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserOrders(ctx)
	return err
}

// PostUserRegister converts echo context to params.
func (w *ServerInterfaceWrapper) PostUserRegister(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PostUserRegister(ctx)
	return err
}

// GetUserBalanceWithdrawals converts echo context to params.
func (w *ServerInterfaceWrapper) GetUserBalanceWithdrawals(ctx echo.Context) error {
	var err error

	ctx.Set(CookieAuthScopes, []string{""})

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetUserBalanceWithdrawals(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/api/user/balance", wrapper.GetUserBalance)
	router.POST(baseURL+"/api/user/balance/withdraw", wrapper.PostUserBalanceWithdraw)
	router.POST(baseURL+"/api/user/login", wrapper.PostUserLogin)
	router.GET(baseURL+"/api/user/orders", wrapper.GetUserOrders)
	router.POST(baseURL+"/api/user/orders", wrapper.PostUserOrders)
	router.POST(baseURL+"/api/user/register", wrapper.PostUserRegister)
	router.GET(baseURL+"/api/user/withdrawals", wrapper.GetUserBalanceWithdrawals)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXT2/bxhP9Kov9/YBeFFNR0kN0qpNDYjSwg7pFD4ZRjMghuQ65u52dtaoG+u7FLkmR",
	"lKn6v5HeKGp2Zt68NzPLbzI1tTUaNTu5/CZdWmIN8fE9VKBT/F1xmRGswytLxiKxwmhgKEMKD7yxKJfS",
	"MSldyO1MOl+H97mhGlguZV4ZYDnrDLWvV0hyu51Jwj+9Iszk8qL115y+3Bmb1RWmHLye4vo310QcJ1KZ",
	"QunJRCw4tzaUTfy5F7zxMTgxlcFZh3gcH9KUPFR3gTzrnibLxsDeTf7lbWUgw+yP4Pw2LG2I2S6xneux",
	"oymIocIt8zeBpp4INd8N6LoVjn6AFLpAQy9T2XbihMrdR5+WTIrOHSrnUwh4L8jN5EMUTD0p3pyHpmsr",
	"bMxXhceey/ArqLp9JWdSQx0csPmKus8FrPoZN3IbHCqdm8aLZkgjNKxBVcHLhlR15W39UxHeHKWm7l1+",
	"CH+K4wJyo811KECGLiVlWZmQwrFwUNsKxfGXE8ElsPAOnQBRmBypBmKhtOASxZlFHYzeHM2Fs5iqXKUQ",
	"vcxkpVLULsqqjfvJkHYCdCY+GXONTnwwtQW9EYujeciCFVfB7nwNRYEkPnbh5ExeI7kmu9dH88bcWNRg",
	"lVzKN/FV6GYuY10TsCrxDilZ9eIuMJZojPUjMitdRDThwA9OtGoU3dEYiSKsk6w5MmybIApnjXYNpYv5",
	"vOOk7R2wtmrLklw5o/vBG57+T5jLpfxf0k/mpB3LyTBMZHyc+7lPg+RyX4lWfQGJySOYoFR0sW3ezl/f",
	"BP5rC1goJ7RhAZ5LQ+pvzMKRHxsU4yMnmpE0VMIhXSMJJDI0krZcXoxFfXG5vQwGNwhJ1sNFY9wENX23",
	"78DsU/HFuCEXu+XVNCo6fm+yzZPRsR9lO54ITB6302p4Md7ezheTRwgFEMYDqI0vSpF7nTlhmj6GNDVe",
	"N0EXiynmr6FSmYgjT/RD//lkslvy09oIpEfoqLkfOdPi+Nzu+ueQRHdJeagUhmy6nSyqzRAbZnImS4QM",
	"KTo6R371odkSozz3bwnbqIf5YTbbgoh27x1SXGceKUm6G5OwoO6vgTHJUU7u1tkMolKOQ4M0l5mRDN2h",
	"+XzWOH/keFaMtbtNBc1FcdsvaSLYPGZiL+Zvb5bj1IgOisiA4XsY7bMD/fnZwN60ONSdA5oOtSfjX5zY",
	"CpS+RfAPbsFhpqIEJ6AihGwjVohadJdosdoILpWLxW1ompiVp7ge+4M0RcuYhT4b0C6fqD3jKOxo7kdG",
	"NH/3WLigDZdIO8R33g6DrJ9vSRAWynH7jdbqcFplv3SW/7E10CHELN6bJyi+p4DeTfVqoXSI3KnApKm3",
	"6mHTwtc10KaTZZN+w4ccc7cef8v96wIIHzoBgjJawMp4jvOy9xAmaLzP3HJXH34/vsReGMZ7ge2wJsX4",
	"yuS5+y5u/dEiHHHRwFP4MC2Z7TJJdl+SR8oETcjt5fafAAAA//+ciLOtnRIAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
