// Package dto provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.11.0 DO NOT EDIT.
package dto

const (
	CookieAuthScopes = "cookieAuth.Scopes"
)

// BalanceWithdraw defines model for BalanceWithdraw.
type BalanceWithdraw struct {
	Order string  `json:"order"`
	Sum   float32 `json:"sum"`
}

// NewUser defines model for NewUser.
type NewUser struct {
	Login    string `json:"login"`
	Password string `json:"password"`
}

// Order1 defines model for Order1.
type Order1 struct {
	Accrual    float32 `json:"accrual"`
	Number     string  `json:"number"`
	Status     string  `json:"status"`
	UploadedAt string  `json:"uploaded_at"`
}

// UserBalance1 defines model for UserBalance1.
type UserBalance1 struct {
	Current   float32 `json:"current"`
	Withdrawn float32 `json:"withdrawn"`
}

// Withdrawals1 defines model for Withdrawals1.
type Withdrawals1 struct {
	Order       string  `json:"order"`
	ProcessedAt string  `json:"processed_at"`
	Sum         float32 `json:"sum"`
}

// PostUserBalanceWithdrawJSONBody defines parameters for PostUserBalanceWithdraw.
type PostUserBalanceWithdrawJSONBody = BalanceWithdraw

// PostUserLoginJSONBody defines parameters for PostUserLogin.
type PostUserLoginJSONBody = NewUser

// PostUserRegisterJSONBody defines parameters for PostUserRegister.
type PostUserRegisterJSONBody = NewUser

// PostUserBalanceWithdrawJSONRequestBody defines body for PostUserBalanceWithdraw for application/json ContentType.
type PostUserBalanceWithdrawJSONRequestBody = PostUserBalanceWithdrawJSONBody

// PostUserLoginJSONRequestBody defines body for PostUserLogin for application/json ContentType.
type PostUserLoginJSONRequestBody = PostUserLoginJSONBody

// PostUserRegisterJSONRequestBody defines body for PostUserRegister for application/json ContentType.
type PostUserRegisterJSONRequestBody = PostUserRegisterJSONBody
